### ISSUE TITLE
ImportError: DLL load failed while importing _ssl  (esp-idf-tools-setup-offline-2.12-beta-03.exe  at win7 Sp1)

### ISSUE THREAD

**Issue by mys812** [espressif/idf-installer#79]
2021-10-17 15:42:03.803   --------
2021-10-17 15:42:03.816   Resetting the repository: D:\tools\Esp32\.espressif\tools\idf-git\2.30.1\cmd\git.exe -C D:\workgroup\ESP32_IDF clean --force -d
2021-10-17 15:42:03.904   Done, exit code=0
2021-10-17 15:42:03.904   --------
2021-10-17 15:42:03.904   Running command: D:\tools\Esp32\.espressif\tools\idf-git\2.30.1\cmd\git.exe -C D:\workgroup\ESP32_IDF clean --force -d
                          
2021-10-17 15:42:03.904   --------
2021-10-17 15:42:03.907   idf_tools.py exists in IDF directory
2021-10-17 15:42:03.907   Offline installation selected. Setting environment variable PIP_NO_INDEX=1
2021-10-17 15:42:03.907   idf_tools.py command: D:\tools\Esp32\.espressif\tools\idf-python\3.8.7\python.exe "D:\workgroup\ESP32_IDF\\tools\idf_tools.py" --idf-path D:\workgroup\ESP32_IDF\
2021-10-17 15:42:03.907   Selection of targets testing command: D:\tools\Esp32\.espressif\tools\idf-python\3.8.7\python.exe "D:\workgroup\ESP32_IDF\\tools\idf_tools.py" install --targets=""
2021-10-17 15:42:04.045   Selection of targets: Supported
2021-10-17 15:42:04.045   Installing tools:D:\tools\Esp32\.espressif\tools\idf-python\3.8.7\python.exe "D:\workgroup\ESP32_IDF\\tools\idf_tools.py" --idf-path D:\workgroup\ESP32_IDF\ install --targets=esp32,esp32-c3,esp32-s3,esp32-s2
2021-10-17 15:42:04.127   Done, exit code=1
2021-10-17 15:42:04.127   --------
2021-10-17 15:42:04.127   Running command: D:\tools\Esp32\.espressif\tools\idf-python\3.8.7\python.exe "D:\workgroup\ESP32_IDF\\tools\idf_tools.py" --idf-path D:\workgroup\ESP32_IDF\ install --targets=esp32,esp32-c3,esp32-s3,esp32-s2
                          Traceback (most recent call last):
                            File "D:\workgroup\ESP32_IDF\\tools\idf_tools.py", line 54, in <module>
                              import ssl
                            File "ssl.py", line 98, in <module>
                          ImportError: DLL load failed while importing _ssl: 参数错误。

**Comment by georgik** [comment]
@mys812 Thank you for reporting the problem.
Please attach also first 10 lines of the installer log. These lines contains diagnostic informations about operating system. Having those information can help us to identify the issue.

It's also helpful to attach information from the second installer screen with System Check.

**Comment by mys812** [comment]
> @mys812 Please check whether your computer does not have installed some older version of Python. More precisely weather environment variable PATH does not contain path to an old Python directory with DLL `libssl-X.Y.dll`
> 
> We were able to simulate similar problem when removing x64 bit version of libssl-1.1.dll from idf-python directory.
> 
> Solution: uninstall old version of Python and run the installer again.

I only install .net framework4.6.2, vscode1.61.0 and Visual C++ Redistributable for Visual Studio 2015 After reinstall Win7.
Not install any version of python an my PC, and i search libssl* at C:/ and d:/, Only found two records below
D:\tools\Esp32\.espressif\tools\idf-git\2.30.1\mingw64\bin\libssl-1_1-x64.dll
D:\tools\Esp32\.espressif\tools\idf-python\3.8.7\libssl-1_1.dll

**Comment by georgik** [comment]
Issue with driver failure installation was fixed in the installer 
- https://github.com/espressif/idf-installer/releases/download/offline-2.12-beta-03/esp-idf-tools-setup-offline-2.12-beta-04.exe

**Comment by georgik** [comment]
@mys812 Thank you for being patient and reporting results of the installation.
We have here two separate issues:
1. problem with failed download with idf-env
2. problem with _ssl in Python

Problem 1.
The download should not happen in case of offline installer. The offline installer should download all files including drivers to .espressif/tools directory. Then the command with install should use this cached files. Yet, what we see is idf-env is still trying to download files and fails for some reason. The installation should not fail in this case, because this is recoverable error.

Problem 2.
This seems like a collision with some other Python. The problem didn't occur after fresh reinstall of Windows 7 x64.

I'll post solution here.

If you're in hurry, you can install ESP-IDF manually:
- install Python 3.8 - it's the last version which works with Windows 7
- install Git
- `git clone --recursive git@github.com:espressif/esp-idf.git`
- cd esp-idf
- install.bat
- export.bat

Now you should have working environment.

To fix the certificate issue I recommend to open Internet Explorer (yes, Internet Explorer, not other browser) and try to open https://dl.espressif.com. This should cause the system to download whole certificate chain. The certificate chain is then tursted by applications like Python. If the connection still fails, please use Firefox to open the site dl.espressif.com. Click the shield and install the certificate into the system. Windows 7 is no longer supported by Microsoft, so these issues with certificates are being more common.

**Comment by georgik** [comment]
I can confirm that the download with idf-env really fails on freshly installed Windows 7 as you reported.

**Comment by georgik** [comment]
@mys812 Using Windows 10 is better option. It's easier to support.

Nevertheless I made further investigation of the problem. It's pretty interesting. The issue is not caused just by missing certificates. The Windows 7 is not able to connect via system API (used for PowerShell, Internet Explorer or Rust Reqwest), because Windows 7 does not support TLS 1.3. https://sockettools.com/kb/windows-and-supported-tls-versions/

That means we can expect the similar issue also on Windows 8.

**Comment by mys812** [comment]
I tried various methods and still cannot successfully install idf-tool on win7. I plan to give up win7 and install win10
